name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        include-prerelease: false
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Clean
      run: dotnet clean
    - name: NuGet clear cache
      run: nuget locals all -clear

    - name: Restore tools
      run: dotnet tool restore
    - name: Check format
      run: dotnet format --verify-no-changes

    - name: Restore dependencies
      run: dotnet restore
    - name: Check dependencies for deprecated packages
      run: dotnet list package --deprecated

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --collect "Code coverage"
